# Generated by Django 4.1.7 on 2024-02-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('u_id', models.IntegerField()),
            ],
            options={
                'ordering': ['lname'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('student_id', models.IntegerField()),
                ('student_advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisees', to='student.advisor')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=3, unique=True)),
                ('course_num', models.CharField(max_length=4, unique=True)),
                ('subject', models.CharField(max_length=15)),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='student.student')),
            ],
            options={
                'ordering': ['dept'],
            },
        ),
    ]
