# Generated by Django 4.1.7 on 2024-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.IntegerField(max_length=4, unique=True),
        ),
    ]
