# Generated by Django 5.0.6 on 2024-07-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_course_description_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True),
        ),
    ]
