# Generated by Django 5.1.6 on 2025-02-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_options_remove_advisor_u_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('dept', 'course_num')},
        ),
    ]
